development:
  adapter: postgresql
  encoding: unicode
  database: oscurrency_development
  pool: 5
  host: localhost
  username: postgres
  password:
  min-messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: oscurrency_test
  pool: 5
  host: localhost
  username: postgres
  password:
  min-messages: warning

production:
  adapter: postgresql
  database: oscurrency
  hostname: localhost
  username: root
  password:


